language: node_js
sudo: false
node_js:
- 0.1
before_script:
- npm rebuild
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: npm test
notifications:
  irc:
    channels:
    - irc.mozilla.org#payments
    on_success: change
    on_failure: always
after_success: npm run-script publish-docker > /dev/null 2>&1
env:
  global:
  - secure: mMNLXed479uVOTmBXudgHVDVtddqKU3YrpMW/vOVeSF7v1rti5OHBCzuJHHWty2stzRhDw/H1PpuA0cuDdO7JsLpmChidJwUP1LTXqUJOXRvGW3XWS8lYp+C/PtitfBn7Zswu3Luy2H1FSiH6042AHCdn7MeSFW1vFOuzFMbjC8=
  - secure: iOnYS97Wu2CwPKoOW6n+UEk96p3Z9SXQ/jJxY3C92pRFzqyIhciuW9Zuhaej3d1fpZW3gvcN9qvgM+RwLaHJHeJgnlB9XWlZDQxysFgnVH6Kcyfx1KnM4KeztgpUWxN7XEOwEQrWBg3Lr72w0i7W7oSSelZAv4WBDIbE0Jg7AGQ=
  - secure: e2y/OC3XQ/s3bUE28org1YuSLRg35DND3Ykd0Qc+7MlvPjwc3Y3s1bvyWUm6N0+Kp3uEgy1g3BJQUsSc5bWWSOWVt0Qyg63DidpgoYZxJgZDH3z2/Aembpxy0OUTv9d5TQqMe7efSZINwrWCKqsDZxGRRdK90TphSiQq/ipkc5U=
